END = -1

# visualize dialog
CHOOSING_SUBJECT_TYPE = 0
CHOOSING_USER_SUBJECT = 1
CHOOSING_LASTFM_SUBJECT = 2
CHOOSING_HOW_MUCH = 3
CHOOSING_PERIOD = 4
CHOOSING_GRAPH = 5
CHOOSING_HOW = 6
CONFIRMATION = 7

# start dialog
START = 100


# configure dialog
CONFIGURE = 200
