END = -1

# start dialog
START = 100

# configure dialog
CONFIGURE = 200

# album dialog
ALBUM_ARTIST_NAME_TYPING = 300
ALBUM_TITLE_TYPING = 301
ALBUM_INFO_SOURCE_DECISION = 302
ALBUM_SPECIFIC_USERNAME_SELECTION = 303
ALBUM_SUBJECT_SELECTION = 304
ALBUM_REPRESENTATION_SELECTION = 305

# user dialog
USER_SOURCE_SELECTION = 400
USER_SPECIFIC_USER_TYPING = 401
USER_SUBJECT_SELECTION = 402
USER_PERIOD_SELECTION = 403
USER_CUSTOM_PERIOD_SELECTION = 404
USER_REPRESENTATION_SELECTION = 405
USER_AMOUNT_SELECTION = 406
