PERIOD_OVERALL = "overall"
PERIOD_7DAYS = "7day"
PERIOD_1MONTH = "1month"
PERIOD_3MONTHS = "3month"
PERIOD_6MONTHS = "6month"
PERIOD_12MONTHS = "12month"

SCROBBLE_SOURCE_USER = "P"
SCROBBLE_SOURCE_NON_PERSONALIZED_BROADCAST = "R"
SCROBBLE_SOURCE_PERSONALIZED_BROADCAST = "E"
SCROBBLE_SOURCE_LASTFM = "L"
SCROBBLE_SOURCE_UNKNOWN = "U"

SCROBBLE_MODE_PLAYED = ""
SCROBBLE_MODE_LOVED = "L"
SCROBBLE_MODE_BANNED = "B"
SCROBBLE_MODE_SKIPPED = "S"


def convert_period(period):
    return {
        'Week': PERIOD_7DAYS,
        'Month': PERIOD_1MONTH,
        'Quarter': PERIOD_3MONTHS,
        'Half a year': PERIOD_6MONTHS,
        'Year': PERIOD_12MONTHS,
        'Overall': PERIOD_OVERALL,
    }.get(period, PERIOD_OVERALL)
